name: "Terraform-Apply-Infra-Release"

on:
    workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash
          working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Cloud Apply
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform cloud apply -auto-approve tfplan